apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: acm
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - acm-default-agent.yaml
  - konflux-common-pipeline-migration-task-template.yaml
  - konflux-batch-migration-cronjob.yaml
  - secrets.yaml